### ISSUE TITLE
Model: too many connections

### ISSUE THREAD

**Issue by HannesRammer** [HannesRammer/Dartabase#10]
while implementing todo list example errors
too many db connections at once in pgsql
check with mysql if problem is adapter specific

using max 5 connections

guessing 
  async loop querying db faster than connection can open and close

thoughts
  maybe keep connections open instead of opening and closing for each query.

**Comment by indiealexh** [comment]
Connection should remain open. Reconnection and handshake and auth adds significant overhead to query time.
